import React from 'react';
import {
  ArrowLeft,
  Ban,
  BookOpen,
  Bot,
  Box,
  CheckCircle2,
  CircleX,
  ClipboardList,
  Clock3,
  Code2,
  Copy,
  Database,
  Eye,
  FlaskConical,
  FolderPlus,
  GitBranch,
  GitFork,
  Globe2,
  Layers3,
  LoaderCircle,
  LockKeyhole,
  MessageSquare,
  Network,
  PauseCircle,
  PenLine,
  Play,
  Plus,
  RefreshCw,
  Repeat2,
  Save,
  ScanText,
  Search,
  Server,
  ShieldCheck,
  Sparkles,
  TestTube2,
  ToggleLeft,
  ToggleRight,
  Trash2,
  UserRoundCheck,
  Workflow,
  Wrench,
  X,
} from 'lucide-react';

const ICONS = {
  active: CheckCircle2,
  back: ArrowLeft,
  ban: Ban,
  'book-open': BookOpen,
  bot: Bot,
  box: Box,
  'circle-check': CheckCircle2,
  'circle-x': CircleX,
  'clipboard-list': ClipboardList,
  clock: Clock3,
  close: X,
  'code-2': Code2,
  configure: PenLine,
  database: Database,
  delete: Trash2,
  eye: Eye,
  'flask-conical': FlaskConical,
  'folder-plus': FolderPlus,
  format: ScanText,
  'git-branch': GitBranch,
  globe: Globe2,
  layers: Layers3,
  loader: LoaderCircle,
  lock: LockKeyhole,
  message: MessageSquare,
  nodes: Network,
  'pause-circle': PauseCircle,
  play: Play,
  plus: Plus,
  retry: RefreshCw,
  save: Save,
  search: Search,
  server: Server,
  sparkles: Sparkles,
  template: Copy,
  test: TestTube2,
  'toggle-left': ToggleLeft,
  'toggle-right': ToggleRight,
  validate: ShieldCheck,
  wrench: Wrench,
  workflow: Workflow,
  'workflow-agent': Bot,
  'workflow-approval': UserRoundCheck,
  'workflow-condition': GitFork,
  'workflow-llm': MessageSquare,
  'workflow-loop': Repeat2,
  'workflow-tool': Wrench,
};

export function AppIcon({ name, size = 14, className = '' }) {
  const Icon = ICONS[name] || Box;
  return <Icon className={`app-icon ${className}`.trim()} size={size} aria-hidden="true" />;
}
